### ISSUE TITLE
Need Lodash 4.17.11?

### ISSUE THREAD

**Issue by rpparas** [zapier/zapier-platform-schema#65]
I'm sorry if this isn't the best place to ask... I'm new to NPM and wanted to learn how to create Zapier integrations. When I tried to install Zapier, my Terminal pointed out an issue with the Lodash dependency: NPM wants me to  [upgrade to v4.17.11.](https://npmjs.com/advisories/782). 
I see it's still 4.17.10 on here... Does the dependency need to be updated here? 

I'm having issues with it even after uninstalling Zapier and Lodash, then re-installing Lodash and Zapier.

![image](https://user-images.githubusercontent.com/592204/53999916-33688400-40fa-11e9-98f0-0a578bb33d2c.png)
![image](https://user-images.githubusercontent.com/592204/53999979-7c203d00-40fa-11e9-8815-7d91ee5c42b3.png) 

https://github.com/zapier/zapier-platform-schema/blob/ab6a601bb648450c361e2ad5352388f0bac2786d/package.json#L32

**Comment by xavdid** [comment]
Hi! great questions. Typically, you don't need to take such a close interest in the packages that get installed, though it doesn't hurt to. for the most part, installed npm packages will "just work". some packages will be duplicated as needed when they're shared, but each package will get something that fits its range. 

As for the security piece, that's a good thing to keep an eye on. In this case it's not a high priority because all of this code is run in an untrusted environment and sandboxed so that you can only mess up your own stuff. Given that, we haven't jumped on bumping it. Good looking out though!
